language: lua

env:
  - LUA=""
  - LUA="luajit"

compiler:
  - gcc

before_script:
  - sudo mkdir -p /usr/local/share/lua/5.1/
  - sudo chmod -R 777 /usr/local

script: "sudo bash travis_install.sh && luajit test.lua && sudo bash install.sh"

branches:
  only:
    - master
    - feature/travis_ci

install:
  - sudo apt-get install luarocks

notifications:
  recipients:
    - iyatomi+ffiex.test@gmail.com
  email:
    on_success: change
    on_failure: always

